name: echowater
description: "Echo water Project"
publish_to: "none"

version: 0.0.6+59

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  table_calendar: ^3.2.0
  intl: ^0.20.2
  flutter_blue_plus: ^1.35.5
  flutter_svg: ^2.2.0
  connectivity_plus: ^6.1.2

  http: ^1.2.1

  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.9.0
  mask_text_input_formatter: 2.9.0
  pin_code_fields: 8.0.1
  cached_network_image: ^3.4.1
  device_info_plus:
  permission_handler: ^11.4.0
  logger: ^2.6.1
  flutter_dotenv: ^5.2.1
  hive_flutter: 1.1.0
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_native_contact_picker: 0.0.10
  share_plus: ^10.1.3

  pull_to_refresh: 2.0.0
  vibration: ^3.1.3
  country_picker: ^2.0.27
  equatable: ^2.0.7
  flutter_cache_manager: ^3.4.1
  local_auth: ^2.3.0
  json_annotation: ^4.9.0
  custom_info_window: 1.0.1
  clippy_flutter: 2.0.0-nullsafety.1
  visibility_detector: 0.4.0+2
  swipe_cards: 2.0.0+1
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  url_launcher: ^6.3.1
  get: ^4.7.2
  google_fonts: ^6.3.0
  image_cropper: ^9.1.0
  lottie: any
  cupertino_icons: 1.0.8
  retrofit: ^4.7.1
  package_info_plus: ^8.1.2
  dio: ^5.9.0
  easy_localization: ^3.0.8
  flutter_local_notifications: ^17.2.4

  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  firebase_messaging: ^16.0.0
  cloud_firestore: ^6.0.0
  firebase_analytics: ^12.0.0
  firebase_performance: ^0.11.0

  screenshot: 3.0.0
  image_painter: 0.7.1
  smooth_page_indicator: ^1.2.1

  widgets_to_image: ^2.0.1

  camera:
  alice: ^1.0.0-dev.12
  alice_dio: ^1.0.4

  flutter_html: ^3.0.0-beta.2

  shimmer: 3.0.0
  flutter_timezone: ^4.1.1

  health: ^13.1.1
  calendar_view: ^1.4.0
  #  kalender: 0.5.0
  klaviyo_flutter: ^0.1.4

  flutter_ota: 0.1.15
  crclib: ^3.0.0
  nordic_dfu: ^7.0.0
  file_picker: ^8.1.3

  wakelock_plus: ^1.3.2

dependency_override:
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^9.2.0
  floor_generator: ^1.5.0
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  build_runner: ^2.5.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/pulse/
    - .dev.env
    - .uat.env
    - .prod.env
    - assets/translations/
    - assets/lottie/
    - assets/images/
    - assets/images/images/
    - assets/images/images/onboarding/
    - assets/icons/
    - assets/icons/svgs/
    - assets/icons/svgs/achievements/
    - assets/images/images/achievements/
    - assets/images/images/streakIcon/

  fonts:
    - family: FieldGothic
      fonts:
        - asset: fonts/FieldGothic-No-74.otf
    - family: FieldGothicTest
      fonts:
        - asset: fonts/FieldGothicTest-No41.otf
        - asset: fonts/FieldGothicTest-No42.otf
          weight: 600
        - asset: fonts/FieldGothicTEST-No-73.otf
          weight: 700
    - family: NimbusSansL
      fonts:
        - asset: fonts/NimbusSanL-Bol.otf
        - asset: fonts/NimbusSanL-BolIta.otf
        - asset: fonts/NimbusSanL-Reg.otf
        - asset: fonts/NimbusSanL-RegIta.otf
    - family: Golos
      fonts:
        - asset: fonts/GolosText-Regular.ttf
