// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPIYSrwuMG9cwAl9ZVJTHSOaPJ5SR8QYo',
    appId: '1:484587939568:android:37bf112b8e65f639790435',
    messagingSenderId: '484587939568',
    projectId: 'echo-water',
    storageBucket: 'echo-water.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBiOfQJx5lm8wm9SZTSeFEAqz7muzK5CVY",
      authDomain: "echo-water.firebaseapp.com",
      projectId: "echo-water",
      storageBucket: "echo-water.appspot.com",
      messagingSenderId: "484587939568",
      appId: "1:484587939568:web:f6ac7fe505564be2790435",
      measurementId: "G-Z1R1X0Q8ED");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEg86U9w3skwUxctQQ-ydBKuraC75Ta0s',
    appId: '1:484587939568:ios:caf1748ad4a940cc790435',
    messagingSenderId: '484587939568',
    projectId: 'echo-water',
    storageBucket: 'echo-water.appspot.com',
    iosBundleId: 'com.outcode.echowater',
  );
}
